import {
  Poppins,
  Luckiest_Guy,
  Shantell_Sans,
  Ubuntu,
  Russo_One,
} from "next/font/google";
import clsx from "clsx";
import "./globals.css";

const poppins_sans = Poppins({
  variable: "--font-poppins-sans",
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
});

const luckies_guy_sans = Luckiest_Guy({
  variable: "--font-luckies-sans",
  subsets: ["latin"],
  weight: ["400"],
});

const shantell_sans = Shantell_Sans({
  variable: "--font-shantell_sans",
  subsets: ["latin", "cyrillic"],
  weight: ["300", "400", "500"],
});

const ubuntu_sans = Ubuntu({
  variable: "--font-ubuntu_sans",
  weight: ["300", "400", "500", "700"],
});

const russo_one_sans = Russo_One({
  variable: "--font-russo-one",
  weight: ["400"],
});

export const metadata = {
  title: "My Portofolio - Erwien Wijaya",
  description: "Generated by next-app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={clsx(
          luckies_guy_sans.variable,
          poppins_sans.variable,
          shantell_sans.variable,
          ubuntu_sans.variable,
          russo_one_sans.variable,
          "antialiased"
        )}
      >
        {children}
      </body>
    </html>
  );
}
